services:
  app:
    # build:
    #   context: .
    platform: linux/amd64
    image: whatwewant/chatgpt-for-chatbot-feishu:v1.2.18
    # command: sleep infinityd
    environment:
      CHATGPT_API_KEY: ${CHATGPT_API_KEY}
      APP_ID: ${APP_ID}
      APP_SECRET: ${APP_SECRET}
      BOT_OPEN_ID: ${BOT_OPEN_ID}
      TUNNEL_ENABLE: "true"
      TUNNEL_TYPE: ${TUNNEL_TYPE}
      TUNNEL_AUTH_TOKEN: ${TUNNEL_AUTH_TOKEN}
      TUNNEL_SUBDOMAIN: ${TUNNEL_SUBDOMAIN}
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
